#ifndef VLC_SPEED_HOLD_CONFIG_H
#define VLC_SPEED_HOLD_CONFIG_H

#define CFG_PREFIX "speed-hold-"

#define MOUSE_BUTTON_CFG CFG_PREFIX "mouse-button"
#define MOUSE_BUTTON_DEFAULT 1 // MOUSE_BUTTON_LEFT

#define ACCELERATION_RATE_CFG CFG_PREFIX "rate"
#define ACCELERATION_RATE_DEFAULT 2.0f

#define HOLD_DELAY_CFG CFG_PREFIX "hold-delay"
#define HOLD_DELAY_DEFAULT 200

#define DISPLAY_SPEED_CFG CFG_PREFIX "display-speed"
#define DISPLAY_SPEED_DEFAULT true

#define REGIONAL_SPEED_CFG CFG_PREFIX "regional-speed"
#define REGIONAL_SPEED_DEFAULT false

#define EDGE_ACCELERATION_RATE_CFG CFG_PREFIX "edge-rate"
#define EDGE_ACCELERATION_RATE_DEFAULT 4.0f

#endif // VLC_SPEED_HOLD_CONFIG_H